apiVersion: v1 
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: pose-app  
  ports:
    - protocol: TCP
      port: 60000
      targetPort: 60000
      nodePort: 30003
